name: wash_it
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.0-279.2.beta <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  get_cli: any
  iconsax: any
  get: 4.6.6
  google_fonts: any
  introduction_screen: any
  http: any
  get_storage: any
  flutter_svg: any
  flutter_rating_bar: ^4.0.1
  dotted_line: ^3.2.2

  firebase_core: any
  firebase_messaging: any

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/bg_boarding/
    - assets/img_home/