name: wash_it
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.0-279.2.beta <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  dotted_line: ^3.2.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_rating_bar: ^4.0.1
  iconsax: ^0.0.8

  get: 4.6.6
  get_cli: ^1.8.4
  get_storage: ^2.1.1
  http: ^1.2.1
  introduction_screen: ^3.1.14
  image_picker: ^1.1.2

  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.1.2
    
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/bg_boarding/
    - assets/img_home/
    - assets/img_chat/